[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'fsharp/vim-fsharp'

[[plugins]]
repo = 'neovim/pynvim'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_func = 'yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_func = 'neovim_rpc'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'itchyny/lightline.vim'
if = "has('gui_running') || &t_Co >= 16"
hook_add = 'call hookadd#lightline()'

[[plugins]]
repo = 'sgur/vim-editorconfig'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'
hook_add = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#buffer#get_source_options({
      \   'name': 'buffer',
      \   'allowlist': ['*'],
      \   'completor': function('asyncomplete#sources#buffer#completor')
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'
hook_add = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#file#get_source_options({
      \   'name': 'file',
      \   'allowlist': ['*'],
      \   'completor': function('asyncomplete#sources#file#completor')
      \ }))
'''

[[plugins]]
repo = 'yami-beta/asyncomplete-omni.vim'
hook_add = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#omni#get_source_options({
      \   'name': 'omni',
      \   'allowlist': ['*'],
      \   'blocklist': ['c', 'cpp', 'html'],
      \   'completor': function('asyncomplete#sources#omni#completor'),
      \   'config': {
      \     'show_source_kind': 1
      \   }
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-emoji.vim'
hook_add = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#emoji#get_source_options({
      \   'name': 'emoji',
      \   'allowlist': ['*'],
      \   'completor': function('asyncomplete#sources#emoji#completor')
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-neosnippet.vim'
depends = 'neosnippet.vim'
hook_add = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#neosnippet#get_source_options({
      \   'name': 'neosnippet',
      \   'allowlist': ['*'],
      \   'completor': function('asyncomplete#sources#neosnippet#completor')
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-emmet.vim'
hook_add = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#emmet#get_source_options({
      \   'name': 'emmet',
      \   'allowlist': ['html'],
      \   'completor': function('asyncomplete#sources#emmet#completor')
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-tags.vim'
hook_add = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#tags#get_source_options({
      \   'name': 'tags',
      \   'allowlist': ['*'],
      \   'completor': function('asyncomplete#sources#tags#completor')
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-necovim.vim'
depends = 'neco-vim'
hook_add = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#necovim#get_source_options({
      \   'name': 'necovim',
      \   'allowlist': ['vim'],
      \   'completor': function('asyncomplete#sources#necovim#completor')
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-necosyntax.vim'
depends = 'neco-syntax'
hook_add = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#necosyntax#get_source_options({
      \   'name': 'necosyntax',
      \   'allowlist': ['*'],
      \   'completor': function('asyncomplete#sources#necosyntax#completor')
      \ }))
'''

[[plugins]]
repo = 'koturn/asyncomplete-dictionary.vim'
hook_add = '''
autocmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#dictionary#get_source_options({
      \   'name': 'dictionary',
      \   'allowlist': ['*'],
      \   'completor': function('asyncomplete#sources#dictionary#completor')
      \ }))
'''

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Mizuchi/STL-Syntax'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'brgmnn/vim-opencl'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'heavenshell/vim-jsdoc'

[[plugins]]
repo = 'janko-m/vim-test'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-django-template'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'koturn/vim-altcomplete'

[[plugins]]
repo = 'koturn/vim-venchmark'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
hook_add = '''
let g:cpp_class_scope_highlight = 1
let g:cpp_experimental_template_highlight = 1
'''

[[plugins]]
repo = 'othree/html5-syntax.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'pocket7878/curses-vim'

[[plugins]]
repo = 'rhysd/tmpwin.vim'

[[plugins]]
repo = 'tatt61880/kuin_vim'
hook_add = 'autocmd MyAutoCmd BufReadPre *.kn  setfiletype kuin'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ujihisa/vimshell-ssh'

[[plugins]]
repo = 'vim-scripts/CCTree'

[[plugins]]
repo = 'vim-scripts/gnuplot.vim'
hook_add = '''
autocmd MyAutoCmd BufReadPre *.plt  setfiletype gnuplot
'''

[[plugins]]
repo = 'osyo-manga/unite-boost-online-doc'

[[plugins]]
repo = 'osyo-manga/unite-highlight'

[[plugins]]
repo = 'sorah/unite-ghq'

[[plugins]]
repo = 'tacroe/unite-mark'

[[plugins]]
repo = 'tsukkee/unite-help'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'ujihisa/unite-font'

[[plugins]]
repo = 'yomi322/unite-tweetvim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
hook_add = '''
let g:lsp_settings_root_markers = [
      \ 'Assembly-CSharp.csproj',
      \ '.git',
      \ '.git/',
      \ '.svn/',
      \ '.hg/',
      \ '.bzr/'
      \]
let g:lsp_settings_servers_dir = expand('~/.vim/vim-lsp-settings/servers')
'''

# [[plugins]]
# repo = 'lighttiger2505/deoplete-vim-lsp'
# depends = ['deoplete.nvim', 'async.vim', 'vim-lsp']

[[plugins]]
repo = 'koturn/vim-shaderlab'

[[plugins]]
repo = 'tikhomirov/vim-glsl'

[[plugins]]
repo = 'DingDean/wgsl.vim'
